### ISSUE TITLE
Unknown file type on normalize

### ISSUE THREAD

**Issue by oliverbrooks** [valobox/epub#6]
```
unknown file type iTunesMetadata.plist
/home/oli/.rvm/gems/ruby-1.9.3-p0-perf@valobox/bundler/gems/rubyzip-f82626867fab/lib/zip/zip_entry.rb:209:in `extract’\n/home/oli/.rvm/gems/ruby-1.9.3-p0-perf@valobox/bundler/gems/rubyzip-f82626867fab/lib/zip/zip_file.rb:187:in `extract’\n/home/oli/.rvm/gems/ruby-1.9.3-p0-perf@valobox/bundler/gems/epub-
```

**Comment by oliverbrooks** [comment]
Similar problem: 

```
Failed to find item in manifest for DejaVuSerif.otf
/home/deploy/web/www.valobox.com/shared/bundle/ruby/1.9.1/bundler/gems/epub-1bca95164f41/lib/epub/item.rb:95:in `get_item’\n/home/deploy/web/www.valobox.com/shared/bundle/ruby/1.9.1/bundler/gems/epub-1bca95164f41/lib/epub/item/css.rb:104:in `block (2 levels) in normalize!‘\n/home/deploy/web/www.valobox.com/shared/bundle/ruby/1.9.1/bundler/gems/epub-1bca95164f41/lib/epub/item/css.rb:93:in `gsub!’\n/home/deploy/web/www.valobox.com/shared/bundle/ruby/1.9.1/bundler/gems/epub-1bca95164f41/lib/epub/item/css.rb:93
```

If the item isn't present can we just let it fail and continue or should we remove the link completely?

**Comment by oliverbrooks** [comment]
If the file is present but not featured in the manifest it is added to the manifest.

If the file is missing the link remains broken and a warning is added to the processing notes
