### ISSUE TITLE
rubyzip-0.9.9: undefined method `exists?' for File:Class

### ISSUE THREAD

**Issue by malikbenkirane** [valobox/epub#8]
I'm new to Ruby, so that might sound very simple, and I might need help to build and set up this gem properly.

Environment: ruby:3.2.2-bullseye

To build the gem, I proceeded this way
```
apt install libmagic-dev
gem build epub.gemspec
gem install epub-0.1.6.gem
```

Then from `irb`
```
require 'epub'
epub = Epub::Document.new("somefile.epub")
```

And I got the following error.
```
/usr/local/bundle/gems/rubyzip-0.9.9/lib/zip/zip_file.rb:65:in `initialize': undefined method `exists?' for File:Class (NoMethodError)

        when ::File.exists?(fileName) && !buffer
                   ^^^^^^^^
Did you mean?  exist?
        from /usr/local/bundle/gems/rubyzip-0.9.9/lib/zip/zip_file.rb:87:in `new'
        from /usr/local/bundle/gems/rubyzip-0.9.9/lib/zip/zip_file.rb:87:in `open'
        from /usr/local/bundle/gems/epub-0.1.6/lib/epub/tools/zip_file.rb:247:in `zip_open'
        from /usr/local/bundle/gems/epub-0.1.6/lib/epub/tools/zip_file.rb:63:in `open'
        from /usr/local/bundle/gems/epub-0.1.6/lib/epub/tools/zip_file.rb:194:in `read'
        from /usr/local/bundle/gems/epub-0.1.6/lib/epub/tools/zip_file.rb:206:in `read_xml'
        from /usr/local/bundle/gems/epub-0.1.6/lib/epub/document.rb:197:in `opf_path'
        from /usr/local/bundle/gems/epub-0.1.6/lib/epub/document.rb:15:in `initialize'
        from (irb):3:in `new'
        from (irb):3:in `<main>'
        from /usr/local/lib/ruby/gems/3.2.0/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'
        from /usr/local/bin/irb:25:in `load'
        from /usr/local/bin/irb:25:in `<main>'
```

I would really appreciate it if anyone can help me understand what happened here.

Many thanks in advance!

**Comment by KitaitiMakoto** [comment]
Hi, welcome to Ruby!

`::File.exists?` method has been deprecated for long time and removed at Ruby 3.2. You need to use `::File.exist?` (`s` is absent) instead.

For use of this library, the best is for the owner to fix it.

But you can monkey-patch by your own:

```ruby
def File.exists?(path)
  ::File.exist?(path)
end

require 'epub'
epub = Epub::Document.new("somefile.epub")

```

You can add (or redefine) existing methods in you code. Here, I added removed `File.exists?` method using existing `File.exist?`.

And, though making an appeal, I also make libraries for EPUB manipulation:
* https://gitlab.com/KitaitiMakoto/epub-parser
* https://gitlab.com/KitaitiMakoto/epub-maker
* and so on...

I appreciate if you try them.
(Sorry for me to make an appeal of my libs at other's repo)
